services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn boj_contest.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - boj_contest_static_volume:/app/staticfiles
      - boj_contest_media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=boj_contest.settings

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
      - boj_contest_static_volume:/staticfiles
      - boj_contest_media_volume:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  boj_contest_static_volume:
  boj_contest_media_volume:
